version: '3.8'

services:
  yocombi-frontend-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: yocombi-frontend-debug
    restart: unless-stopped
    ports:
      - "3003:80"  # Port debug différent
    environment:
      - FLUTTER_WEB_USE_SKIA=false
      - API_BASE_URL=http://184.174.39.92:8080/v1
      - NODE_ENV=debug
    networks:
      - yocombi-debug-network

networks:
  yocombi-debug-network:
    driver: bridge
