version: '3.8'

services:
  # YoCombifront - Development Environment
  yocombifront-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: yocombifront-dev
    ports:
      - "3000:8080"  # Changed from 8080 to 3000
    volumes:
      - .:/app
      - /app/.dart_tool
      - /app/build
      - yocombi_node_modules:/app/node_modules
    environment:
      - FLUTTER_WEB_USE_SKIA=true
      - NODE_ENV=development
      - DEVELOPER_IDENTIFIER=${DEVELOPER_IDENTIFIER:-yocombi-dev}
      - GIT_COMMIT_HASH=${GIT_COMMIT_HASH:-local-dev}
      - GIT_BRANCH=${GIT_BRANCH:-develop}
      - BUILD_VARIANT=yocombi-dev
      - API_BASE_URL=http://184.174.39.92:8081/v1  # Using 8081 instead of 8080
    networks:
      - yocombifront-network
    stdin_open: true
    tty: true
    restart: unless-stopped

  # YoCombifront - Production Environment
  yocombifront-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: yocombifront-prod
    ports:
      - "3001:80"  # Production on port 3001
    environment:
      - BUILD_VARIANT=yocombi-prod
      - API_BASE_URL=http://184.174.39.92:8081/v1  # Using 8081 instead of 8080
    networks:
      - yocombifront-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  yocombi_node_modules:

networks:
  yocombifront-network:
    driver: bridge